<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Share</name>
   <tag></tag>
   <elementGuidId>732d413a-c471-4a22-9a98-27d3f2c47560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/center/div/div[2]/div[6]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1e83761-786b-44d2-ba99-b4fd1e2d9375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card py-8 px-8 max-w-sm mx-auto space-y-2 bg-white rounded-xl shadow-lg items-center sm:space-y-0 sm:gap-x-6</value>
      <webElementGuid>779f5423-c83d-4b3a-8d28-8bf301e29688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Share</value>
      <webElementGuid>509a6026-8302-4bc8-904e-a978ce5f0df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiContainer-root MuiContainer-disableGutters dashboard css-jj1crp&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg boxContainer css-1gvdw8w&quot;]/center[1]/div[@class=&quot;tilesBox MuiBox-root css-n9yb05&quot;]/div[@class=&quot;MuiGrid2-root MuiGrid2-container MuiGrid2-direction-xs-row MuiGrid2-spacing-xs-2 css-1klpoq2&quot;]/div[@class=&quot;MuiGrid2-root MuiGrid2-direction-xs-row MuiGrid2-grid-lg-4 MuiGrid2-grid-xs-6 css-1is2k5f&quot;]/div[@class=&quot;custom-col&quot;]/div[@class=&quot;card py-8 px-8 max-w-sm mx-auto space-y-2 bg-white rounded-xl shadow-lg items-center sm:space-y-0 sm:gap-x-6&quot;]</value>
      <webElementGuid>3566df97-46ff-434d-a60b-dc8bcd428d5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/center/div/div[2]/div[6]/div/div</value>
      <webElementGuid>f9763511-b8b8-46e1-93b4-38796c7f4f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep track of new contests, your referral stats, and more.'])[1]/following::div[25]</value>
      <webElementGuid>e97f4b91-fc67-4b21-942a-567dacceb764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[2]</value>
      <webElementGuid>34af7b3b-08b0-4ddb-bb56-f7f662a26b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[2]</value>
      <webElementGuid>aa7d0309-3797-41e6-a341-61c50d09ead6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div</value>
      <webElementGuid>d6b84e44-764b-48e6-a834-a674aaf3a9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Share' or . = 'Share')]</value>
      <webElementGuid>efde108f-72ad-440f-ba37-ac0d62befbde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
