<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Welcome_message</name>
   <tag></tag>
   <elementGuidId>ecddb295-c2c2-4fb0-8d8b-70cfcc36ca96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/center/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.my-4.welcome-line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e12a4eb9-b58b-4810-892b-07b2a33e0d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-4 welcome-line</value>
      <webElementGuid>1f7639f2-f012-48f1-89a8-4742017fd400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hi siva, welcome to your ISR dec 26 Experience!</value>
      <webElementGuid>b21e0ea1-c861-4062-b38a-58ca62c36cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiContainer-root MuiContainer-disableGutters dashboard css-jj1crp&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg boxContainer css-1gvdw8w&quot;]/center[1]/div[@class=&quot;tilesBox MuiBox-root css-n9yb05&quot;]/div[@class=&quot;items-center custom-row typography&quot;]/h1[@class=&quot;my-4 welcome-line&quot;]</value>
      <webElementGuid>e50916c7-12ff-4e04-8cd3-894bc6fb0856</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/center/div/div/h1</value>
      <webElementGuid>153be1a3-30c0-4022-ab2f-7c4d9a43ff99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep track of new contests, your referral stats, and more.'])[1]/preceding::h1[1]</value>
      <webElementGuid>1677f623-d2a1-48a8-a889-33c1b378ba90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::h1[1]</value>
      <webElementGuid>3b1b2938-1792-4a46-9c51-1601549c2151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hi']/parent::*</value>
      <webElementGuid>61f40524-627a-44fd-8f28-80e813c64630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>90ec8f4a-d605-4b0f-969f-8475e1d8e1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Hi siva, welcome to your ISR dec 26 Experience!' or . = 'Hi siva, welcome to your ISR dec 26 Experience!')]</value>
      <webElementGuid>7f6a4bc8-8c0e-46fc-803a-71b55a7a3fd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
