<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_pointscount</name>
   <tag></tag>
   <elementGuidId>568a0f03-8912-472c-a23f-a6102fab7216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div/div[2]/div/div[3]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.MuiTypography-root.MuiTypography-body1._title_xk5is_23.css-9gc6di</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e8828053-786d-40dd-ba14-2de9301147a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 _title_xk5is_23 css-9gc6di</value>
      <webElementGuid>2fadc624-de30-4392-abd6-f08bac33f305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>721d692e-0ea4-4aaf-9aa1-65b1c9acb597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_headerContainer_1x5uc_1&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-disableGutters css-jj1crp&quot;]/div[@class=&quot;MuiBox-root css-n9yb05&quot;]/div[@class=&quot;MuiGrid2-root MuiGrid2-container MuiGrid2-direction-xs-row MuiGrid2-spacing-xs-2 _header_1x5uc_1 css-kqf5nf&quot;]/div[@class=&quot;MuiGrid2-root MuiGrid2-direction-xs-row MuiGrid2-grid-xs-12 MuiGrid2-grid-md-4 css-kymykv&quot;]/div[@class=&quot;_cardContainer_xk5is_6&quot;]/div[3]/p[@class=&quot;MuiTypography-root MuiTypography-body1 _title_xk5is_23 css-9gc6di&quot;]</value>
      <webElementGuid>f1420556-731b-4a33-8e90-46ab9ec66c3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div[2]/div/div[3]/p</value>
      <webElementGuid>7acf5c83-7651-45f1-b56a-7c470741307f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep track of new contests, your referral stats, and more.'])[1]/preceding::p[2]</value>
      <webElementGuid>a1012eaf-b7ae-4d7d-9860-469c976014b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10']/parent::*</value>
      <webElementGuid>72e0fe05-b881-4966-a5a0-85362b1f0c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>b2a093d5-8363-41c1-90bc-e66d80ceca92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '10' or . = '10')]</value>
      <webElementGuid>a34d4440-bd46-4061-8c89-98e01eb0728c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
